module: GetCreditwaveToken  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (105.27.231.9:9094)  26/02/2026 06:56:19
module: SendSMSOTPs  Error:  startIndex ('-3') must be a non-negative value. (Parameter 'startIndex')
Actual value was -3.  26/02/2026 06:56:34
module: SendSMSOTPs  Error:     at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at API.Infrastructure.Application.Communication.Communication.ProcessSMS() in D:\Playground\source\DMIT\IPP\FuseGate\API.Infrastructure\API.Infrastructure\Application\Communication\Communication.cs:line 68  26/02/2026 06:56:34
module: Partner code AuthenticatePartner  Error:  LATBS9Y  26/02/2026 07:10:56
module: GetCreditwaveToken  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (105.27.231.9:9094)  26/02/2026 07:11:20
module: SendCreditwaveSMSAsync  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (105.27.231.9:9094)  26/02/2026 07:11:20
module: Partner code AuthenticatePartner  Error:  LATBS9Y  26/02/2026 11:30:43
module: CompleteActivation  Error:  Data is Null. This method or property cannot be called on Null values.  26/02/2026 11:39:32
module: CompleteActivation  Error:  Data is Null. This method or property cannot be called on Null values.  26/02/2026 11:41:54
module: GetCreditwaveToken  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (105.27.231.9:9094)  26/02/2026 11:45:33
module: SendCreditwaveSMSAsync  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (105.27.231.9:9094)  26/02/2026 11:45:33
