module: Partner code AuthenticatePartner  Error:  LATBS9Y  20/01/2026 18:13:03
module: GetQuote  Error:  Invalid column name 'PartnerCode'.
Invalid column name 'LATBS9Y'.  20/01/2026 18:13:29
module: GetQuote  Error:  Invalid column name 'PartnerCode'.
Invalid column name 'LATBS9Y'.  20/01/2026 18:14:29
module: GetQuote  Error:  Invalid column name 'PartnerCode'.  20/01/2026 18:16:58
module: GetQuote  Error:  Invalid object name 'dbo.MsureRequests'.  20/01/2026 18:59:31
module: GetQuote  Error:  Invalid object name 'dbo.MsureRequests'.  20/01/2026 18:59:37
