module: OnBoarding  Error:  Error in OnBoarding: Invalid column name 'MemberNumber'.  20/03/2026 08:31:50
module: Partner code AuthenticatePartner  Error:  LATBS9Y  20/03/2026 09:09:26
module: AddBeneficiaries  Error:  The entity type 'BeneficiaryDetailsDTO' was not found. Ensure that the entity type has been added to the model.  20/03/2026 09:20:59
module: AddBeneficiaries  Error:  The entity type 'BeneficiaryDetailsDTO' was not found. Ensure that the entity type has been added to the model.  20/03/2026 09:26:52
module: AddBeneficiaries  Error:  Invalid object name 'gurdians'.  20/03/2026 09:29:22
