module: addleads  Error:  Error in addleads: Invalid column name 'product'.
Invalid column name 'OtherDetails'.  17/02/2026 05:17:19
module: Partner code AuthenticatePartner  Error:  LATBS9Y  17/02/2026 17:33:48
module: OnBoarding  Error:  Error in OnBoarding: Invalid column name 'AverageIncome'.  17/02/2026 17:36:40
module: OnBoarding  Error:  Error in OnBoarding: Invalid column name 'AverageIncome'.  17/02/2026 17:36:49
module: OnBoarding  Error:  Error in OnBoarding: Invalid column name 'AverageIncome'.  17/02/2026 17:39:54
module: OnBoarding  Error:  Error in OnBoarding: Invalid column name 'AverageIncome'.  17/02/2026 17:40:03
module: OnBoarding  Error:  Error in OnBoarding: Invalid column name 'AverageIncome'.  17/02/2026 17:49:49
module: OnBoarding  Error:  Error in OnBoarding: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.  17/02/2026 17:59:03
module: OnBoarding  Error:  Error in OnBoarding: Unable to cast object of type 'System.String' to type 'System.Int32'.  17/02/2026 18:08:48
module: OnBoarding  Error:  Error in OnBoarding: Unable to cast object of type 'System.String' to type 'System.Int32'.  17/02/2026 18:09:21
module: OnBoarding  Error:  Error in OnBoarding: Unable to cast object of type 'System.String' to type 'System.Int32'.  17/02/2026 18:18:44
module: OnBoarding  Error:  Error in OnBoarding: Unable to cast object of type 'System.String' to type 'System.Int32'.  17/02/2026 19:21:02
module: InsertCustomerProductAsync  Error:  Error in InsertCustomerProductAsync: An error occurred while saving the entity changes. See the inner exception for details.  17/02/2026 19:21:48
module: InsertCustomerProductAsync  Error:  Error in InsertCustomerProductAsync: An error occurred while saving the entity changes. See the inner exception for details.  17/02/2026 19:25:05
