module: Partner code AuthenticatePartner  Error:  LATBS9Y  04/03/2026 10:22:38
module: Partner code AuthenticatePartner  Error:  LATBS9Y  04/03/2026 10:24:23
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 12:55:43
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 14:26:49
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 14:26:59
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 14:27:09
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 14:27:20
module: AuthenticatePartner  Error:  Invalid object name 'dbo.APIUSERS'.  04/03/2026 14:27:20
module: AuthenticatePartner  Error:  Invalid object name 'dbo.APIUSERS'.  04/03/2026 14:27:28
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 14:27:31
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 14:27:41
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 14:27:51
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 14:28:09
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 14:28:23
module: AuthenticatePartner  Error:  Invalid object name 'dbo.APIUSERS'.  04/03/2026 14:30:06
module: SendSMSOTPs  Error:  Procedure or function 'getOTPs' expects parameter '@smsType', which was not supplied.  04/03/2026 14:30:19
module: Partner code AuthenticatePartner  Error:  LATBS9Y  04/03/2026 14:33:19
module: MpesaTransactionManager -QueryToken  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (api.safaricom.co.ke:443)  04/03/2026 15:01:27
module: MpesaTransactionManager -QueryToken  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (sandbox.safaricom.co.ke:443)  04/03/2026 15:41:26
module: SendSMSOTPs  Error:  Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.  04/03/2026 15:43:36
module: SendSMSOTPs  Error:  Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.  04/03/2026 15:47:17
module: MpesaTransactionManager -QueryToken  Error:  The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.  04/03/2026 15:55:15
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  04/03/2026 16:14:19
