module: Partner code AuthenticatePartner  Error:  LATBS9Y  12/03/2026 13:51:27
module: MpesaTransactionManager -QueryToken  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (sandbox.safaricom.co.ke:443)  12/03/2026 13:56:34
module: MpesaTransactionManager -QueryToken  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (sandbox.safaricom.co.ke:443)  12/03/2026 13:56:34
module: MpesaTransactionManager -QueryToken  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (sandbox.safaricom.co.ke:443)  12/03/2026 13:56:34
module: MpesaTransactionManager -QueryToken  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (sandbox.safaricom.co.ke:443)  12/03/2026 13:56:34
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  12/03/2026 13:57:52
module: Partner code AuthenticatePartner  Error:  LATBS9Y  12/03/2026 15:30:21
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  12/03/2026 15:33:55
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  12/03/2026 16:09:56
module: MpesaTransactionManager -QueryToken  Error:  An attempt was made to access a socket in a way forbidden by its access permissions. (sandbox.safaricom.co.ke:443)  12/03/2026 17:12:05
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  12/03/2026 17:12:09
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  12/03/2026 17:12:26
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  12/03/2026 17:13:01
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  12/03/2026 17:13:15
