module: Partner code AuthenticatePartner  Error:  LATBS9Y  13/03/2026 07:39:44
module: Partner code AuthenticatePartner  Error:  LATBS9Y  13/03/2026 07:40:09
module: MpesaTransactionManager -QueryToken  Error:  The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.  13/03/2026 08:01:09
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  13/03/2026 08:04:49
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  13/03/2026 08:06:04
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  13/03/2026 08:24:36
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  13/03/2026 08:25:43
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  13/03/2026 08:43:16
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  13/03/2026 08:45:18
module: MpesaTransactionManager -QueryToken  Error:  An error occurred while saving the entity changes. See the inner exception for details.  13/03/2026 08:46:37
