module: OnboardingRequest  Error:  An error occurred while saving the entity changes. See the inner exception for details.  18/10/2025 18:48:55
module: OnboardingRequest  Error:  An error occurred while saving the entity changes. See the inner exception for details.  18/10/2025 18:49:38
module: OnboardingRequest  Error:  There are more columns in the INSERT statement than values specified in the VALUES clause. The number of values in the VALUES clause must match the number of columns specified in the INSERT statement.  18/10/2025 18:50:28
module: OnboardingRequest  Error:  Conversion failed when converting the varchar value 'e1b0df46-92a2-451c-a9ff-5b327596df84' to data type int.  18/10/2025 19:36:24
module: OnboardingRequest  Error:  Cannot insert the value NULL into column 'Id', table 'FuseGate.dbo.CreditLifeRequests'; column does not allow nulls. INSERT fails.
The statement has been terminated.  18/10/2025 19:37:19
