module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjA1MDgwNjMyMzA=","Timestamp":"20260508063230","TransactionType":"CustomerPayBillOnline","Amount":"1","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://api.sanlam.co.ke/uatncbampesacallback","AccountReference":"25-KPUQ8C","TransactionDesc":"1236cc1f-3a51-4a50-c1a0-08deacc9ac22"}  08/05/2026 18:32:34
module: RequestMpesaExpress  Info:  {
            "MerchantRequestID":"09d0-438a-bb3f-e47f70e631b01277182",
            "CheckoutRequestID":"ws_CO_08052026183235416715315447",
            "ResponseCode": "0",
            "ResponseDescription":"Success. Request accepted for processing",
            "CustomerMessage":"Success. Request accepted for processing"
        }
          08/05/2026 18:32:34
