module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMDQwMzQwNDg=","Timestamp":"20260304034048","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://rw2s4xr8-8909.uks1.devtunnels.ms/processpensionstkresult","AccountReference":"26-NQ9N9T","TransactionDesc":"bc6fab58-1878-4538-59a6-08de79eb37ea"}  04/03/2026 15:57:53
module: RequestMpesaExpress  Info:  {
                    "requestId":"5faa-4a2d-99fe-fc9329bdbba0263341",
                    "errorCode": "404.001.03",
                    "errorMessage": "Invalid Access Token"
                }
              04/03/2026 15:57:55
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMDQwNDEyMjI=","Timestamp":"20260304041222","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://rw2s4xr8-8909.uks1.devtunnels.ms/processpensionstkresult","AccountReference":"26-NQ9N9T","TransactionDesc":"6d97a8cc-8e39-45b7-59a7-08de79eb37ea"}  04/03/2026 16:17:13
module: RequestMpesaExpress  Info:  {
                    "requestId":"2dfd-472d-9bbd-df490884098d439417",
                    "errorCode": "404.001.03",
                    "errorMessage": "Invalid Access Token"
                }
              04/03/2026 16:17:34
