module: GenerateToken  Info:  Unauthorized access attempt from IP: 0.0.0.1  08/04/2026 10:48:05
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjA0MDgxMDU1MzY=","Timestamp":"20260408105536","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://api.sanlam.co.ke/uatncbampesacallback","AccountReference":"26-3ZRVML","TransactionDesc":"5fadcda0-b6bb-46a3-f0f6-08de954433ec"}  08/04/2026 10:55:37
module: RequestMpesaExpress  Info:  {
            "MerchantRequestID":"aede-454a-9955-505396794ace11994938",
            "CheckoutRequestID":"ws_CO_08042026105538973715315447",
            "ResponseCode": "0",
            "ResponseDescription":"Success. Request accepted for processing",
            "CustomerMessage":"Success. Request accepted for processing"
        }
          08/04/2026 10:55:37
