module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTMwODA0NDU=","Timestamp":"20260313080445","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://api.sanlam.co.ke/uatncbampesacallback","AccountReference":"26-NQ9N9T","TransactionDesc":"7c850a8e-2a4c-4e43-3168-08de80be0b27"}  13/03/2026 08:04:49
module: RequestMpesaExpress  Info:  {
            "MerchantRequestID":"0e92-4449-a979-1dd5f78d3a2c684217",
            "CheckoutRequestID":"ws_CO_13032026080452247715315447",
            "ResponseCode": "0",
            "ResponseDescription":"Success. Request accepted for processing",
            "CustomerMessage":"Success. Request accepted for processing"
        }
          13/03/2026 08:04:52
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTMwODA1NTY=","Timestamp":"20260313080556","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://api.sanlam.co.ke/uatncbampesacallback","AccountReference":"26-NQ9N9T","TransactionDesc":"b5024f25-da8d-4194-3169-08de80be0b27"}  13/03/2026 08:06:14
module: RequestMpesaExpress  Info:  {
            "MerchantRequestID":"9f7a-4cef-8b38-8d306fb3c0091181627",
            "CheckoutRequestID":"ws_CO_13032026080618605715315447",
            "ResponseCode": "0",
            "ResponseDescription":"Success. Request accepted for processing",
            "CustomerMessage":"Success. Request accepted for processing"
        }
          13/03/2026 08:06:42
module: ProcessPensionSTKResult  Info:  test  13/03/2026 08:12:16
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTMwODI0MzI=","Timestamp":"20260313082432","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://api.sanlam.co.ke/uatncbampesacallback","AccountReference":"26-NQ9N9T","TransactionDesc":"2269f6c1-691a-48f1-d1f8-08de80c0ccf4"}  13/03/2026 08:24:36
module: RequestMpesaExpress  Info:  {
            "MerchantRequestID":"5ee0-4adc-9304-640ff1126f8a1292582",
            "CheckoutRequestID":"ws_CO_13032026082440340715315447",
            "ResponseCode": "0",
            "ResponseDescription":"Success. Request accepted for processing",
            "CustomerMessage":"Success. Request accepted for processing"
        }
          13/03/2026 08:24:40
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTMwODI1Mjg=","Timestamp":"20260313082528","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://api.sanlam.co.ke/uatncbampesacallback","AccountReference":"26-NQ9N9T","TransactionDesc":"2269f6c1-691a-48f1-d1f8-08de80c0ccf4"}  13/03/2026 08:25:52
module: RequestMpesaExpress  Info:  {
            "MerchantRequestID":"5ee0-4adc-9304-640ff1126f8a1294757",
            "CheckoutRequestID":"ws_CO_13032026082556230715315447",
            "ResponseCode": "0",
            "ResponseDescription":"Success. Request accepted for processing",
            "CustomerMessage":"Success. Request accepted for processing"
        }
          13/03/2026 08:25:57
module: ProcessPensionSTKResult  Info:  test  13/03/2026 08:27:50
module: ProcessPensionSTKResult  Info:  {
    "Body": {
        "stkCallback": {
            "MerchantRequestID": "5ee0-4adc-9304-640ff1126f8a1294757",
            "CheckoutRequestID": "ws_CO_13032026082556230715315447",
            "ResultCode": 0,
            "ResultDesc": "The service request is processed successfully.",
            "CallbackMetadata": {
                "Item": [
                    {
                        "Name": "Amount",
                        "Value": 100.00
                    },
                    {
                        "Name": "MpesaReceiptNumber",
                        "Value": "NLJ7RT61SV"
                    },
                    {
                        "Name": "TransactionDate",
                        "Value": 20191219102115
                    },
                    {
                        "Name": "PhoneNumber",
                        "Value": 254708374149
                    }
                ]
            }
        }
    }
}  13/03/2026 08:27:57
module: ProcessPensionSTKResult  Info:  test  13/03/2026 08:35:21
module: ProcessPensionSTKResult  Info:  {
    "Body": {
        "stkCallback": {
            "MerchantRequestID": "5ee0-4adc-9304-640ff1126f8a1294757",
            "CheckoutRequestID": "ws_CO_13032026082556230715315447",
            "ResultCode": 0,
            "ResultDesc": "The service request is processed successfully.",
            "CallbackMetadata": {
                "Item": [
                    {
                        "Name": "Amount",
                        "Value": 100.00
                    },
                    {
                        "Name": "MpesaReceiptNumber",
                        "Value": "NLJ7RT61SV"
                    },
                    {
                        "Name": "TransactionDate",
                        "Value": 20191219102115
                    },
                    {
                        "Name": "PhoneNumber",
                        "Value": 254708374149
                    }
                ]
            }
        }
    }
}  13/03/2026 08:35:24
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTMwODQzMTI=","Timestamp":"20260313084312","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://api.sanlam.co.ke/uatncbampesacallback","AccountReference":"26-NQ9N9T","TransactionDesc":"9eb9a698-6880-426e-9c09-08de80c36a49"}  13/03/2026 08:43:16
module: RequestMpesaExpress  Info:  {
            "MerchantRequestID":"3dd8-41fc-9d89-89252b4cce03566555",
            "CheckoutRequestID":"ws_CO_13032026084321994715315447",
            "ResponseCode": "0",
            "ResponseDescription":"Success. Request accepted for processing",
            "CustomerMessage":"Success. Request accepted for processing"
        }
          13/03/2026 08:43:20
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTMwODQ1MTU=","Timestamp":"20260313084515","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://api.sanlam.co.ke/uatncbampesacallback","AccountReference":"26-NQ9N9T","TransactionDesc":"6af31da5-dc94-4a67-9c0a-08de80c36a49"}  13/03/2026 08:45:18
module: RequestMpesaExpress  Info:  {
            "MerchantRequestID":"0e92-4449-a979-1dd5f78d3a2c754806",
            "CheckoutRequestID":"ws_CO_13032026084522274715315447",
            "ResponseCode": "0",
            "ResponseDescription":"Success. Request accepted for processing",
            "CustomerMessage":"Success. Request accepted for processing"
        }
          13/03/2026 08:45:21
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTMwODQ2MzQ=","Timestamp":"20260313084634","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://api.sanlam.co.ke/uatncbampesacallback","AccountReference":"26-NQ9N9T","TransactionDesc":"1774e673-71c5-4519-9c0b-08de80c36a49"}  13/03/2026 08:46:37
module: RequestMpesaExpress  Info:  {
            "MerchantRequestID":"3dd8-41fc-9d89-89252b4cce03572637",
            "CheckoutRequestID":"ws_CO_13032026084641338715315447",
            "ResponseCode": "0",
            "ResponseDescription":"Success. Request accepted for processing",
            "CustomerMessage":"Success. Request accepted for processing"
        }
          13/03/2026 08:46:40
module: ProcessPensionSTKResult  Info:  test  13/03/2026 08:48:01
module: ProcessPensionSTKResult  Info:  {
    "Body": {
        "stkCallback": {
            "MerchantRequestID": "3dd8-41fc-9d89-89252b4cce03572637",
            "CheckoutRequestID": "ws_CO_13032026084641338715315447",
            "ResultCode": 0,
            "ResultDesc": "The service request is processed successfully.",
            "CallbackMetadata": {
                "Item": [
                    {
                        "Name": "Amount",
                        "Value": 100.00
                    },
                    {
                        "Name": "MpesaReceiptNumber",
                        "Value": "NLJ7RT61SV"
                    },
                    {
                        "Name": "TransactionDate",
                        "Value": 20191219102115
                    },
                    {
                        "Name": "PhoneNumber",
                        "Value": 254708374149
                    }
                ]
            }
        }
    }
}  13/03/2026 08:48:07
