module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjA0MTkwNTMxMzU=","Timestamp":"20260419053135","TransactionType":"CustomerPayBillOnline","Amount":"100","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://api.sanlam.co.ke/uatncbampesacallback","AccountReference":"26-AFLMM3Q","TransactionDesc":"eebb91c9-3610-4564-a037-497e1f35a07b"}  19/04/2026 17:32:04
module: RequestMpesaExpress  Info:  {
            "MerchantRequestID":"bd6b-451f-b915-8c19b1d150981981459",
            "CheckoutRequestID":"ws_CO_19042026173205923715315447",
            "ResponseCode": "0",
            "ResponseDescription":"Success. Request accepted for processing",
            "CustomerMessage":"Success. Request accepted for processing"
        }
          19/04/2026 17:32:10
