module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTIwMTU2MzM=","Timestamp":"20260312015633","TransactionType":"CustomerPayBillOnline","Amount":"5","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://rw2s4xr8-8909.uks1.devtunnels.ms/processpensionstkresult","AccountReference":"26-NQ9N9T","TransactionDesc":"f66c65c4-815d-48a2-d734-08de8025fecb"}  12/03/2026 13:56:34
module: RequestMpesaExpress  Info:  {
                    "requestId":"d247-4a0c-98ff-486b9670556c11946",
                    "errorCode": "404.001.03",
                    "errorMessage": "Invalid Access Token"
                }
              12/03/2026 13:56:37
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTIwMTU3NDA=","Timestamp":"20260312015740","TransactionType":"CustomerPayBillOnline","Amount":"5","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://rw2s4xr8-8909.uks1.devtunnels.ms/processpensionstkresult","AccountReference":"26-NQ9N9T","TransactionDesc":"2ee5f33e-b0ac-4c75-d735-08de8025fecb"}  12/03/2026 13:58:12
module: RequestMpesaExpress  Info:  {
                    "requestId":"7db1-415e-ad98-4d5af0b5bd2835533",
                    "errorCode": "404.001.03",
                    "errorMessage": "Invalid Access Token"
                }
              12/03/2026 13:58:16
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTIwMzMyMzk=","Timestamp":"20260312033239","TransactionType":"CustomerPayBillOnline","Amount":"3","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://rw2s4xr8-8909.uks1.devtunnels.ms/processpensionstkresult","AccountReference":"26-NQ9N9T","TransactionDesc":"eeca1dd0-d462-4032-5f63-08de80336a76"}  12/03/2026 15:34:05
module: RequestMpesaExpress  Info:  {
                    "requestId":"aea7-4f88-8004-157bb4b4ba5e10535",
                    "errorCode": "404.001.03",
                    "errorMessage": "Invalid Access Token"
                }
              12/03/2026 15:34:24
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTIwNDA5NTQ=","Timestamp":"20260312040954","TransactionType":"CustomerPayBillOnline","Amount":"3","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://rw2s4xr8-8909.uks1.devtunnels.ms/processpensionstkresult","AccountReference":"26-NQ9N9T","TransactionDesc":"c8632713-a67e-42fe-abc0-08de8038a445"}  12/03/2026 16:10:03
module: RequestMpesaExpress  Info:  {
                    "requestId":"1b63-45f6-a9ff-c5dddb3e0d542954",
                    "errorCode": "404.001.03",
                    "errorMessage": "Invalid Access Token"
                }
              12/03/2026 16:10:05
module: RequestMpesaExpress  Info:  {"BusinessShortCode":"65102","Password":"NjUxMDI5ZWUxYjdkNThhMDdlMDRkNDA3YmQyY2QzZGE1M2UyNTY3MzdmNjczODRhNTE0MzBmNWEzNTNhMmE2ZjIxNDk0MjAyNjAzMTIwNTExNTg=","Timestamp":"20260312051158","TransactionType":"CustomerPayBillOnline","Amount":"3","PartyA":"254715315447","PartyB":"65102","PhoneNumber":"254715315447","CallBackURL":"https://rw2s4xr8-8909.uks1.devtunnels.ms/processpensionstkresult","AccountReference":"26-NQ9N9T","TransactionDesc":"80d6643c-cc49-408a-4705-08de804147eb"}  12/03/2026 17:13:31
module: RequestMpesaExpress  Info:  {
                    "requestId":"180b-48f3-b6e2-fb856a64d54a21950",
                    "errorCode": "404.001.03",
                    "errorMessage": "Invalid Access Token"
                }
              12/03/2026 17:13:34
